name: ravl
channels:
  - conda-forge
  - bioconda
dependencies:
  # naavre-fl-*-cell-build
  - r-jsonlite>=1.9.1
  - r-optparse>=1.7.5
  # naavre-fl-*-jupyter
  - ipykernel>=6.29.5
  - r-irkernel>=1.3.2
  # user packages for all flavors
  - git>=2.39.1
  - minio>=7.2.15
  - pip>=25.0.1
  - python>=3.8
  - r>=4.3
  - r-secretsprovider
  - r-getpass
  - pip:
    - SecretsProvider
  # user packages for this flavor
  - h5py
  - webdavclient3
  - r-base
  - hdf5
  - pkg-config
  - gdal
  - libgdal
  - libgdal-hdf5
  - openssl
  - proj
  - gsl
  - r-raster
  - r-sf
  - libexpat
  - udunits2
  - bioconductor-rhdf5
  - r-labeling
  - r-bit64
  - r-progress
  - r-cli
  - r-colorspace
  - r-rcolorbrewer
  - r-matrix
  - r-fansi
  - r-dotcall64
  - r-nlme
  - r-munsell
  - r-generics
  - r-tibble
  - r-spam
  - r-maps
  - r-isoband
  - r-mgcv
  - r-scales
  - r-gtable
  - r-utf8
  - r-munsell
  - r-withr
  - r-timechange
  - r-clipr
  - r-vroom
  - r-tzdb
  - r-stringi
  - r-purrr
  - r-curl
  - r-dplyr
  - r-fields
  - r-ggplot2
  - r-lubridate
  - r-stringr
  - r-tidyr
  - r-tidyselect
  - r-viridis
  - r-readr
  - r-gridextra
  - r-classint
  - r-s2
  - r-proxy
  - r-sf
  - r-wk
  - r-udunits2
  - r-renv
  - r-lobstr
  - r-rlang
  - r-rcpp
  - r-rcppeigen
  - nano
  - vim
  - r::r-lutz