install.packages("modisfast", repos="https://cran.r-project.org")
library("modisfast")
install.packages("appeears", repos="https://cran.r-project.org")
library("appeears")
devtools::install_github("mapoflife/rstoat", dependencies = FALSE)
library("rstoat")
install.packages("rsi", repos="https://cran.r-project.org")
library("rsi")
install.packages("stacr", repos="https://cran.r-project.org")
library("stacr")
