name: laserfarm
channels:
  - conda-forge
dependencies:
  # naavre-fl-*-cell-build
  # - r-jsonlite=1.9.1
  # - r-optparse=1.7.5
  # naavre-fl-*-jupyter
  - ipykernel>=6.29.5
  # - r-irkernel=1.3.2
  # user packages for all flavors
  - git>=2.39.1
  - minio>=7.2.15
  - pip>=25.0.1
  - python>=3.8
  # - r=4.4
  # user packages for this flavor
  - asyncssh
  - cxx-compiler
  - dask
  - dask-core
  - distro
  - gcc=12.1.0
  - gdal=3.5.0
  - html5lib
  - Jinja2
  - laspy
  - lazrs-python
  - libgcc
  - libstdcxx-ng
  - matplotlib
  - numpy
  - pdal
  - plyfile
  - pyshp
  - python-pdal
  - scipy
  - sentinelhub
  - setuptools
  - shapely
  - webdavclient3
  - wradlib
  - pip:
      - git+https://github.com/QCDIS/Laserfarm.git
      - git+https://github.com/QCDIS/laserchicken.git
