name: Make flavor

on:
  workflow_call:
    inputs:
      flavor_name:
        description: 'NaaVRE flavor name'
        type: string
        required: true
      image_repo:
        description: 'Docker image repo'
        type: string
        required: true
      ci_image_version:
        description: 'Docker image version for CI'
        type: string
        required: true
      rel_image_version:
        description: 'Docker image version for release'
        type: string
        required: true
      build_jupyter:
        description: 'Whether to build the NaaVRE Jupyter images'
        type: boolean
        required: true
      build_cell_base:
        description: 'Whether to build the NaaVRE cell base images'
        type: boolean
        required: true
      free_disk_space:
        description: 'Free disk space on the action runner before running jobs'
        type: boolean
        required: true

jobs:
  configure-workflow:
    name: Configure workflow
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        name: Configure skip-duplicate-actions
        uses: fkirc/skip-duplicate-actions@v5
        with:
          paths: '[".github/**", "docker/**", "flavors/${{ inputs.flavor_name }}/**"]'
          do_not_skip: '["workflow_dispatch", "schedule", "release"]'

  build-cell-build:
    uses: ./.github/workflows/build-image.yaml
    needs: [configure-workflow]
    if: ${{ needs.configure-workflow.outputs.should_skip != 'true' && inputs.build_cell_base }}
    with:
      dockerfile: cell-build.Dockerfile
      flavor_dir: './flavors/${{ inputs.flavor_name }}'
      image_name: naavre-fl-${{ inputs.flavor_name }}-cell-build
      image_repo: ${{ inputs.image_repo }}
      image_version: ${{ inputs.ci_image_version }}

  build-cell-runtime:
    uses: ./.github/workflows/build-image.yaml
    needs: [configure-workflow]
    if: ${{ needs.configure-workflow.outputs.should_skip != 'true' && inputs.build_cell_base }}
    with:
      dockerfile: cell-runtime.Dockerfile
      flavor_dir: './flavors/${{ inputs.flavor_name }}'
      image_name: naavre-fl-${{ inputs.flavor_name }}-cell-runtime
      image_repo: ${{ inputs.image_repo }}
      image_version: ${{ inputs.ci_image_version }}

  build-jupyter:
    uses: ./.github/workflows/build-image.yaml
    needs: [configure-workflow]
    if: ${{ needs.configure-workflow.outputs.should_skip != 'true' && inputs.build_jupyter }}
    with:
      dockerfile: jupyter.Dockerfile
      flavor_dir: './flavors/${{ inputs.flavor_name }}'
      image_name: naavre-fl-${{ inputs.flavor_name }}-jupyter
      image_repo: ${{ inputs.image_repo }}
      image_version: ${{ inputs.ci_image_version }}
      free_disk_space: ${{ inputs.free_disk_space }}

  test-jupyter:
    uses: ./.github/workflows/test-jupyter.yaml
    needs: [configure-workflow, build-jupyter]
    if: needs.configure-workflow.outputs.should_skip != 'true'
    with:
      image_name: naavre-fl-${{ inputs.flavor_name }}-jupyter
      image_repo: ${{ inputs.image_repo }}
      image_version: ${{ inputs.ci_image_version }}
      tests_dir: './flavors/${{ inputs.flavor_name }}/tests/'

  test-naavre-cell:
    uses: ./.github/workflows/test-naavre-cell.yaml
    needs: [configure-workflow, build-cell-build, build-cell-runtime]
    if: needs.configure-workflow.outputs.should_skip != 'true'
    with:
      image_name_build: naavre-fl-${{ inputs.flavor_name }}-cell-build
      image_name_runtime: naavre-fl-${{ inputs.flavor_name }}-cell-runtime
      image_name: naavre-fl-${{ inputs.flavor_name }}-cell-test
      image_repo: ${{ inputs.image_repo }}
      image_version: ${{ inputs.ci_image_version }}
      tests_dir: './flavors/${{ inputs.flavor_name }}/tests/'

  push-cell-build:
    uses: ./.github/workflows/push-image.yaml
    needs: [configure-workflow, build-cell-build, test-jupyter, test-naavre-cell]
    if: ${{ needs.configure-workflow.outputs.should_skip != 'true' && github.event_name == 'release' && inputs.build_cell_base }}
    with:
      image_name: naavre-fl-${{ inputs.flavor_name }}-cell-build
      image_repo: ${{ inputs.image_repo }}
      ci_image_version: ${{ inputs.ci_image_version }}
      rel_image_version: ${{ inputs.rel_image_version }}

  push-cell-runtime:
    uses: ./.github/workflows/push-image.yaml
    needs: [configure-workflow, build-cell-runtime, test-jupyter, test-naavre-cell]
    if: ${{ needs.configure-workflow.outputs.should_skip != 'true' && github.event_name == 'release' && inputs.build_cell_base }}
    with:
      image_name: naavre-fl-${{ inputs.flavor_name }}-cell-runtime
      image_repo: ${{ inputs.image_repo }}
      ci_image_version: ${{ inputs.ci_image_version }}
      rel_image_version: ${{ inputs.rel_image_version }}

  push-jupyter:
    uses: ./.github/workflows/push-image.yaml
    needs: [configure-workflow, build-jupyter, test-jupyter, test-naavre-cell]
    if: ${{ needs.configure-workflow.outputs.should_skip != 'true' && github.event_name == 'release' && inputs.build_jupyter }}
    with:
      image_name: naavre-fl-${{ inputs.flavor_name }}-jupyter
      image_repo: ${{ inputs.image_repo }}
      ci_image_version: ${{ inputs.ci_image_version }}
      rel_image_version: ${{ inputs.rel_image_version }}
      free_disk_space: ${{ inputs.free_disk_space }}