name: Test cell base image

on:
  workflow_call:
    inputs:
      image_name_build:
        description: 'Docker image name for build stage'
        type: string
        required: true
      image_name_runtime:
        description: 'Docker image name for runtime stage'
        type: string
        required: true
      image_name:
        description: 'Docker image name'
        type: string
        required: true
      image_repo:
        description: 'Docker image repo'
        type: string
        required: true
      image_version:
        description: 'Docker image version'
        type: string
        required: true
      tests_dir:
        description: 'Directory containing test files'
        type: string
        required: true

jobs:
  test:
    name: Test ${{ inputs.image_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docker
        run: |
          docker build \
            . \
            -f docker/cell-test.Dockerfile \
            --build-arg BUILD_IMAGE=${{ inputs.image_repo }}/${{ inputs.image_name_build }}:${{ inputs.image_version }} \
            --build-arg RUNTIME_IMAGE=${{ inputs.image_repo }}/${{ inputs.image_name_runtime }}:${{ inputs.image_version }} \
            -t ${{ inputs.image_repo }}/${{ inputs.image_name }}:${{ inputs.image_version }} \
            --cache-from type=gha \
            --cache-to type=gha,mode=min \

      - name: Run tests
        run: |
          docker run -v ${{ inputs.tests_dir }}:/tests/ ${{ inputs.image_repo }}/${{ inputs.image_name }}:${{ inputs.image_version }} /bin/bash /tests/tests.sh
